### ISSUE TITLE
International API

### ISSUE THREAD

**Issue by jaysig** [cayasso/smartystreets-api#1]
Is there a way to specify the International vs. US API?

**Comment by cayasso** [comment]
Hi @jaysig currently only the US API is supported because its what we needed for our project, but this should be easy to implement by following the [international api](https://smartystreets.com/docs/international-street-api) but currently I don't have the time to dedicate for a feature like this, however I am open for PRs from the community to improve the project ;-)

**Comment by cayasso** [comment]
Closing this for now
